def check_topic(topic_id):
        
    TOPIC = {
        '/m/04rlf' : '음악',
        '/m/05fw6t' : '동요',
        '/m/02mscn' : '찬송가',
        '/m/0ggq0m' : '클래식',
        '/m/01lyv' : '국가',
        '/m/02lkt' : '일렉트로닉',
        '/m/0glt670' : '힙합',
        '/m/05rwpb' : '인디',
        '/m/03_d0' : '재즈',
        '/m/028sqc' : 'Music of Asia',
        '/m/0g293' : 'Music of Latin America',
        '/m/064t9' : '팝송',
        '/m/06cqb' : '레게',
        '/m/06j6l' : 'Rhythm and blues',
        '/m/06by7' : '락',
        '/m/0gywn' : 'Soul music',
        '/m/0bzvm2' : 'Gaming',
        '/m/025zzc' : 'Action game',
        '/m/02ntfj' : 'Action-adventure game',
        '/m/0b1vjn' : 'Casual game',
        '/m/02hygl' : 'Music video game',
        '/m/04q1x3q' : 'Puzzle video game',
        '/m/01sjng' : 'Racing video game',
        '/m/0403l3g' : 'Role-playing video game',
        '/m/021bp2' : 'Simulation video game',
        '/m/022dc6' : 'Sports game',
        '/m/03hf_rm' : 'Strategy video game',
        '/m/06ntj' : '스포츠',
        '/m/0jm_' : 'American football',
        '/m/018jz' : '야구',
        '/m/018w8' : '배드민턴',
        '/m/01cgz' : 'Boxing',
        '/m/09xp_' : 'Cricket',
        '/m/02vx4' : '풋볼',
        '/m/037hz' : '골프',
        '/m/03tmr' : '아이스하키',
        '/m/01h7lh' : 'Mixed martial arts',
        '/m/0410tth' : 'Motorsport',
        '/m/066wd' : 'Professional wrestling',
        '/m/07bs0' : '테니스',
        '/m/07_53' : '발리볼',
        '/m/02jjt' : 'Entertainment',
        '/m/095bb' : '만화영화',
        '/m/09kqc' : 'Humor',
        '/m/02vxn' : '영화',
        '/m/05qjc' : 'Performing arts',
        '/m/019_rr' : 'Lifestyle',
        '/m/032tl' : '패션',
        '/m/027x7n' : 'Fitness',
        '/m/02wbm' : '음식',
        '/m/0kt51' : '건강',
        '/m/03glg' : '취미',
        '/m/068hy' : '애완동물',
        '/m/041xxh' : 'Physical attractiveness [Beauty]',
        '/m/07c1v' : '과학기술',
        '/m/07bxq' : '관광',
        '/m/07yv9' : 'Vehicles',
        '/m/01k8wb' : '지식',
        '/m/098wr' : '사회',
    }

    return TOPIC[topic_id]
    #print(topic_id)