# Generated by Django 2.2.5 on 2019-10-07 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=30)),
                ('keyword', models.CharField(blank=True, max_length=30, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('subscribers', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
        ),
    ]
